environment: 
  RESEND_API_KEY: ${RESEND_API_KEY}
  TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
  AUDIENCE_ID: ${AUDIENCE_ID}
  
packages:
  - name: api
    functions:
      - name: sendEmail
        runtime: 'go:1.20'
      - name: addContact
        runtime: 'go:1.20'    
        