environment: 
  RESEND_API_KEY: ${RESEND_API_KEY}
  
packages:
  - name: functions
    functions:
      - name: send-email
        runtime: 'go:1.20'
        environment:
          TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      - name: add-contact
        runtime: 'go:1.20'
        environment:
          AUDIENCE_ID: ${AUDIENCE_ID}
        