environment: 
  RESEND_API_KEY: ${RESEND_API_KEY}
  
packages:
  - name: functions
    functions:
      - name: sendEmail
        runtime: 'go:1.20'
        environment:
          TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      - name: addContact
        runtime: 'go:1.20'
        environment:
          AUDIENCE_ID: ${AUDIENCE_ID}
        