alerts:
- rules: DEPLOYMENT_FAILED
- rules: DOMAIN_FAILED

functions:
- github:
    branch: main
    deploy_on_push: true
    repo: codepumper/functions
  routes:
    - path: /api
  name: api
  source_dir: /
  envs:
  - key: AUDIENCE_ID
    scope: RUN_TIME
  - key: TO_EMAIL_ADDRESS
    scope: RUN_TIME
  - key: RESEND_API_KEY
    scope: RUN_TIME
name: api
