alerts:
- rules: DEPLOYMENT_FAILED
- rules: DOMAIN_FAILED
functions:

- name: add-contact
  github:
    branch: main
    deploy_on_push: true
    repo: codepumper/functions
  routes:
  - path: /add-contact
    function: add-contact

- name: send-email
  github:
    branch: main
    deploy_on_push: true
    repo: codepumper/functions
  routes:
  - path: /send-email
    function: send-email
  
