name: functions
services:
  - name: send-email-function
    git:
      repo_clone_url: https://github.com/codepumper/functions.git
      branch: main
      deploy_on_push: true
    environment_slug: go
    routes:
      - path: ./email
        handler: ./main
        type: http

