spec:
  alerts:
  - rules: DEPLOYMENT_FAILED
  - rules: DOMAIN_FAILED
  functions:
  - github:
      branch: main
      deploy_on_push: true
      repo: codepumper/functions
    name: email
     routes:
    - path: /email
    source_dir: /
  name: url
