alerts:
- rules: DEPLOYMENT_FAILED
- rules: DOMAIN_FAILED
functions:
- name: functions
  github:
    branch: main
    deploy_on_push: true
    repo: codepumper/functions
  routes:
  - path: /functions/sendEmail
    function: sendEmail
  - path: /functions/addContact
    function: addContact
  
