name: Deploy to DigitalOcean Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Go function
      run: go build -o main ./sendTransactionalEmail

    - name: Login to DigitalOcean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Deploy function
      run: |
        doctl functions deploy your-function-name \
          --entrypoint ./main \
          --runtime go1.20 \
          --region your-region \
          --source .

